PR#1 from team-staging
grepthink/grepthink pull request #244
Opened 2019-03-04 05:27 UTC by Kapn

PR consists of:
* Theme switching -- added theme field to profile. Changes color of left navbar
* Project Desired Technologies
* Ability to view other students schedules
* Schedule displays day/week/month options.
* Other small bugs that were assigned to calendar team.

_Note: Had to comment js theme switcher for now until more functional._

2019-03-14 20:03 UTC, rmonroe approved these changes

2019-03-15 17:14 UTC, Kapn commented on teamwork/templates/adminlte/lib/_main_header.html
> +<!-- add this style for Light/Dark theme -->
is this style used?

2019-04-10 07:35 UTC, rmonroe requested changes
Need to remove 
https://github.com/grepthink/grepthink/pull/244/commits/7f664883454213c24255e67123fc94b562fe5f63
https://github.com/grepthink/grepthink/pull/244/commits/3ecf0039378b2933c56ef989a4b6a645eea5a05b

2019-05-28 23:55 UTC, closed without merging

2019-05-28 23:56 UTC, rmonroe commented
Deprecated